In [18]:
#Roey Stern
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

In [2]:
iris = pd.read_csv('iris.csv')

In [3]:
iris.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [4]:
iris['Species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [5]:
# creating a 2d array for the analysis 
len(iris['SepalLengthCm'])
l = []
for index, value in iris['SepalLengthCm'].items():
    l.append(value)
w = []
for index, value in iris['SepalWidthCm'].items():
    w.append(value)
   
Sepal_l_w = list(zip(l,w))

In [6]:
# Predicting the species based on the Sepal Length and Width

X = Sepal_l_w
y = iris['Species']

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=36)

In [8]:
#SVM model: 
from sklearn.linear_model import SGDClassifier
model_SVM = SGDClassifier()

model_SVM.fit(X_train,y_train)
pred_SVM = model_SVM.predict(X_test)
print(pred_SVM)
print(y_test)
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score
print(accuracy_score(pred_SVM, y_test))

['Iris-virginica' 'Iris-virginica' 'Iris-virginica' 'Iris-virginica'
 'Iris-virginica' 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa'
 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-virginica' 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-virginica' 'Iris-setosa' 'Iris-virginica'
 'Iris-setosa' 'Iris-virginica' 'Iris-virginica' 'Iris-setosa'
 'Iris-virginica' 'Iris-setosa' 'Iris-setosa' 'Iris-virginica'
 'Iris-setosa' 'Iris-virginica']
50     Iris-versicolor
145     Iris-virginica
86     Iris-versicolor
118     Iris-virginica
122     Iris-virginica
57     Iris-versicolor
56     Iris-versicolor
51     Iris-versicolor
69     Iris-versicolor
66     Iris-versicolor
59     Iris-versicolor
4          Iris-setosa
110     Iris-virginica
94     Iris-versicolor
29         Iris-setosa
35         Iris-setosa
28         Iris-setosa
77     Iris-versicolor
14         Iris-setosa
146     Iris-virginica
48         Iris-setosa
125     Iris-virginica
102     Iris-v

In [9]:
print(precision_score(pred_SVM, y_test,average='macro'))
print(recall_score(pred_SVM, y_test,average='macro'))
print(f1_score(pred_SVM, y_test,average='macro'))


0.7272727272727272
0.7802197802197802
0.663059163059163


In [10]:
from sklearn.model_selection import cross_val_score

cross_val_score(model_SVM,X_train,y_train,cv=5,scoring='accuracy')

array([0.70833333, 0.625     , 0.70833333, 0.70833333, 0.5       ])

In [16]:
#Confusion Matrix for SVM
from sklearn.metrics import confusion_matrix
confusion_matrix(pred_SVM,y_test)
#It appears that Iris-setosa and Iris-versicolor are most often confused with each other.

array([[ 8,  5,  1],
       [ 0,  3,  0],
       [ 0,  3, 10]])

In [13]:
# Logistic Regression

model_LR = SGDClassifier(loss='log')

model_LR.fit(X_train,y_train)
pred_LR = model_LR.predict(X_test)

print(accuracy_score(pred_LR, y_test))
print(precision_score(pred_LR, y_test, average='macro'))
print(recall_score(pred_LR, y_test, average='macro'))
print(f1_score(pred_LR, y_test, average='macro'))

0.7333333333333333
0.7575757575757577
0.7714285714285715
0.7492877492877493


In [14]:
cross_val_score(model_LR,X_train,y_train,cv=5,scoring='accuracy')

array([0.45833333, 0.41666667, 0.58333333, 0.83333333, 0.75      ])

In [17]:
#Confusion Matrix for LR
from sklearn.metrics import confusion_matrix
confusion_matrix(pred_LR,y_test)
#It appears that Iris-versicolor and Iris-virginica are most often confused with each other

array([[8, 0, 0],
       [0, 9, 6],
       [0, 2, 5]])